# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Venus-Protocol

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Clear
        run: docker container prune -f && docker image prune -f
      - name: Build docker
        run: docker build -t venus:${GITHUB_SHA::7} .
      - name: Lint
        run: docker run --name ${GITHUB_SHA::7} venus:${GITHUB_SHA::7} lint
      - name: Clear
        run: docker rm ${GITHUB_SHA::7}
      - name: Run compound tests
        run: docker run --name ${GITHUB_SHA::7} venus:${GITHUB_SHA::7} test
      - name: Clear
        run: docker rm ${GITHUB_SHA::7}
